### ISSUE TITLE
Default timeout type is wrong

### ISSUE THREAD

**Issue by sibeshkar** [mayahq/maya-red-browser-automation#13]
![image](https://user-images.githubusercontent.com/8736797/120041110-578b4500-c025-11eb-86d2-d3c0edaca165.png)
This should be of type `number`, not `msg`

**Comment by shubham-root** [comment]
@sibeshkar which node is this?

**Comment by sibeshkar** [comment]
Query node

**Comment by shubham-root** [comment]
Fixed and updated master and release.
